<?php

namespace App\Console\Commands;

use App\Events\OpeninghoursUpdated;
use App\Models\Calendar;
use App\Models\Channel;
use App\Models\Event;
use App\Models\Openinghours;
use Illuminate\Console\Command;

class FetchRecreatex extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'openinghours:fetch-recreatex';

    /**
     * The SHOP ID for the RECREATEX service
     *
     * @var string
     */
    protected $shopId;

    /**
     * The Recreatex SOAP URI
     *
     * @var string
     */
    protected $recreatexUri;

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Fetch RECREATEX openinghours data';

    /**
     * The start of the calendar
     * @var string
     */
    const CALENDAR_START = '2017-01-01';

    /**
     * The end of the calendar
     * @var string
     */
    const CALENDAR_END = '2020-01-01';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();

        $this->shopId = env('SHOP_ID');
        $this->recreatexUri = env('RECREATEX_URI');

        if (empty($this->shopId)) {
            throw new \Exception("No shop ID was found, we can't fetch openinghours from the RECREATEX webservice without it.
                You can configure a shop ID in the .env file.");
        }

        if (empty($this->recreatexUri)) {
            throw new \Exception("No recreatexUri was found, we can't fetch openinghours from the RECREATEX webservice without it.
                You can configure a recreatexUri in the .env file.");
        }
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $recreatexServices = app('ServicesRepository')->where('source', 'recreatex')->get();

        foreach ($recreatexServices as $recreatexService) {
            if (! empty($recreatexService->identifier)) {
                $openinghoursList = $this->getOpeninghours($recreatexService->identifier);

                // If openinghours were found, create a channel for the service
                // and add the events passed in $openinghoursList to an openinghours object
                // of the channel, the default channel is called "Algemeen"
                if (! empty($openinghoursList) && ! $this->serviceHasAutogeneratedChannel($recreatexService)) {
                    $channel = new Channel();
                    $channel->label = 'Algemeen';

                    // Link the channel to the service
                    $recreatexService->channels()->save($channel);

                    $openinghours = new Openinghours();
                    $openinghours->active = true;
                    $openinghours->start_date = self::CALENDAR_START;
                    $openinghours->end_date = self::CALENDAR_END;
                    $openinghours->label = 'Geïmporteerde kalender ' . $openinghours->start_date . ' - ' . $openinghours->end_date;

                    // Link the openinghours to the channel
                    $channel->openinghours()->save($openinghours);

                    $calendar = new Calendar();
                    $calendar->priority = 0;
                    $calendar->closinghours = 0;
                    $calendar->label = 'Openingsuren';

                    // Link the calendar to the openinghours
                    $openinghours->calendars()->save($calendar);

                    $sequenceNumber = 1;

                    foreach ($openinghoursList as $openinghourEvent) {
                        if (! empty($openinghourEvent['From1']) && ! empty($openinghourEvent['To1'])) {
                            $event = new Event();
                            $event->rrule = 'FREQ=YEARLY';
                            $event->start_date = $openinghourEvent['From1'];
                            $event->end_date = $openinghourEvent['To1'];
                            $event->label = $sequenceNumber;
                            $event->until = $openinghourEvent['Date'];

                            // Link event to the calendar
                            $calendar->events()->save($event);
                        }

                        if (! empty($openinghourEvent['From2']) && ! empty($openinghourEvent['To2'])) {
                            $event = new Event();
                            $event->rrule = 'FREQ=YEARLY';
                            $event->start_date = $openinghourEvent['From2'];
                            $event->end_date = $openinghourEvent['To2'];
                            $event->label = $sequenceNumber;
                            $event->until = $openinghourEvent['Date'];

                            // Link event to the calendar
                            $calendar->events()->save($event);
                        }

                        $sequenceNumber++;
                    }

                    event(new OpeninghoursUpdated($openinghours->id));
                } else {
                    $this->info('The service ' . $recreatexService->identifier . " already has a channel 'Algemeen', therefore we did not import any openinghours for this specific service.");
                }
            }
        }
    }

    /**
     * Determine if the service has a channel called "Algemeen"
     *
     * @param  Eloquent $service
     * @return boolean
     */
    private function serviceHasAutogeneratedChannel($service)
    {
        $channels = $service->channels;

        if (empty($channels)) {
            return false;
        }

        return $channels->contains(function ($value) {
            return $value->label == 'Algemeen';
        });
    }

    /**
     * Fetch the recreatex openinghours for a certain infrastructure
     *
     * @param  string $recreatexId
     * @return array
     */
    private function getOpeninghours($recreatexId)
    {
        $soapBody = $this->makeSoapBody($recreatexId);

        $headers = [
            'Content-type: text/xml;charset="utf-8"',
            'Accept: text/xml',
            'Cache-Control: no-cache',
            'Pragma: no-cache',
            'SOAPAction:  http://www.recreatex.be/webshop/v3.8/IWebShop/FindInfrastructureOpenings',
            'Content-length: ' . strlen($soapBody),
        ];

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_URL, $this->recreatexUri);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
        curl_setopt($ch, CURLOPT_TIMEOUT, 20);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $soapBody);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $response = curl_exec($ch);

        curl_close($ch);

        // Remove the SOAP envelop
        $response = str_replace('<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body>', '', $response);
        $response = str_replace('</s:Body></s:Envelope>', '', $response);

        $xml = simplexml_load_string($response);
        $json = json_encode($xml);
        $fullJson = json_decode($json, true);

        // Parse the InfrastructureOpeningHours from the body
        return array_get($fullJson, 'InfrastructureOpeningHours.InfrastructureOpeningHours.OpenHours.OpeningHour', []);
    }

    private function makeSoapBody($recreatexId)
    {
        return '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v3="http://www.recreatex.be/webshop/v3.8/">
                   <soapenv:Header/>
                   <soapenv:Body>
                      <v3:Context>
                         <v3:ShopId>' . $this->shopId . '</v3:ShopId>
                      </v3:Context>
                      <v3:InfrastructureOpeningsSearchCriteria>
                         <v3:InfrastructureId>' . $recreatexId . '</v3:InfrastructureId>
                         <v3:From>2017-01-01T00:00:00.8115784+02:00</v3:From>
                         <v3:Until>2020-01-01T00:00:00.8115784+02:00</v3:Until>
                      </v3:InfrastructureOpeningsSearchCriteria>
                   </soapenv:Body>
                </soapenv:Envelope>';
    }
}
