#!/bin/bash
# PHP CodeSniffer pre-commit hook for git
#

# Default return code.
RETVAL=0

# Run unit tests.
OUTPUT="$(php vendor/bin/robo test)"

if [ $? -ne 0 ]; then
   echo
   echo -e "\033[00;41;37m                                                                      \033[0m"
   echo -e "\033[00;41;37m  ✘ Error(s) during coder checks!                                     \033[0m"
   echo -e "\033[00;41;37m                                                                      \033[0m"
   echo
   RETVAL=1
fi


# Return result of all checks.
exit $RETVAL
