engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
exclude_paths:
- public/js/chunks/*
- resources/assets/sass/vendor/*
- yarn.lock
- gulpfile.js
