engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
      Naming/BooleanGetMethodName:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
exclude_paths:
- public/js/chunks/*
- resources/assets/sass/vendor/*
- yarn.lock
- gulpfile.js
- tests/*
