language: php

php:
  - 5.6.30

before_script:
  - cp .env.travis .env
  - mysql -e 'create database openinghours;'
  - composer self-update
  - composer install --no-interaction
  - ./vendor/bin/robo digipolis:install-laravel
  - php artisan db:seed

script:
  - vendor/bin/phpunit
